<?php

namespace App\Services;

class BuddhistCalendarService
{
    /**
     * Get list of Buddhist Holy Days & Major Lunar Events.
     */
    public static function getHolidays(): array
    {
        return [
            // --- TAHUN 2025 ---
            [
                'date' => '2025-02-12',
                'title' => 'Hari Suci Magha Puja 2568 TB',
                'type' => 'holiday',
                'category' => 'Hari Raya Buddhis',
                'badge' => 'Magha Puja',
                'description' => 'Peringatan berkumpulnya 1.250 Arahat tanpa diundang, serta pembabaran prinsip dasar ajaran Buddha (Ovāda Pāṭimokkha).',
                'is_major' => true,
            ],
            [
                'date' => '2025-05-12',
                'title' => 'Hari Raya Trisuci Waisak 2569 TB',
                'type' => 'holiday',
                'category' => 'Hari Raya Buddhis',
                'badge' => 'Trisuci Waisak',
                'description' => 'Momentum agung memperingati tiga peristiwa suci: Kelahiran Pangeran Siddharta, Pencapaian Pencerahan Sempurna, dan Mahaparinibbana Buddha Gautama.',
                'is_major' => true,
            ],
            [
                'date' => '2025-07-10',
                'title' => 'Hari Suci Asadha Puja 2569 TB',
                'type' => 'holiday',
                'category' => 'Hari Raya Buddhis',
                'badge' => 'Asadha Puja',
                'description' => 'Peringatan pemutaran Roda Dhamma pertama kali (Dhammacakkappavattana Sutta) di Taman Rusa Isipatana dan terbentuknya Sangha pertama.',
                'is_major' => true,
            ],
            [
                'date' => '2025-10-07',
                'title' => 'Masa Kathina Dāna 2569 TB',
                'type' => 'holiday',
                'category' => 'Hari Raya Buddhis',
                'badge' => 'Kathina Dāna',
                'description' => 'Bulan persembahan jubah kathina dan kebutuhan pokok bagi Bhikkhu Sangha yang telah menyelesaikan masa vassa.',
                'is_major' => true,
            ],

            // --- TAHUN 2026 ---
            [
                'date' => '2026-03-03',
                'title' => 'Hari Suci Magha Puja 2569 TB',
                'type' => 'holiday',
                'category' => 'Hari Raya Buddhis',
                'badge' => 'Magha Puja',
                'description' => 'Peringatan berkumpulnya 1.250 Arahat tanpa diundang, ditahbiskan langsung oleh Sang Buddha (Ehi Bhikkhu), serta pembabaran Ovāda Pāṭimokkha.',
                'is_major' => true,
            ],
            [
                'date' => '2026-05-31',
                'title' => 'Hari Raya Trisuci Waisak 2570 TB',
                'type' => 'holiday',
                'category' => 'Hari Raya Buddhis',
                'badge' => 'Trisuci Waisak',
                'description' => 'Peringatan Tiga Peristiwa Agung: Kelahiran Pangeran Siddharta (623 SM), Penerangan Agung Menjadi Buddha (588 SM), dan Mahāparinibbāna Sang Buddha (543 SM).',
                'is_major' => true,
            ],
            [
                'date' => '2026-07-29',
                'title' => 'Hari Suci Asadha Puja 2570 TB',
                'type' => 'holiday',
                'category' => 'Hari Raya Buddhis',
                'badge' => 'Asadha Puja',
                'description' => 'Peringatan Pemutaran Roda Pembebasan (Dhammacakkappavattana Sutta) kepada 5 pertapa dan kemunculan Tiratana (Buddha, Dhamma, Sangha) secara lengkap.',
                'is_major' => true,
            ],
            [
                'date' => '2026-10-25',
                'title' => 'Hari Raya Kathina Dāna 2570 TB & Pavāranā',
                'type' => 'holiday',
                'category' => 'Hari Raya Buddhis',
                'badge' => 'Kathina Dāna',
                'description' => 'Perayaan persembahan jubah suci Kathina dan sanghadāna kepada Bhikkhu Sangha setelah usai melaksanakan masa vassa selama tiga bulan.',
                'is_major' => true,
            ],

            // Hari Uposatha Bulanan 2026 (Purnama & Tilem)
            [
                'date' => '2026-01-03',
                'title' => 'Hari Uposatha Bulan Purnama (Purnamasiddhi)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Purnama',
                'description' => 'Hari melatih kemoralan 8 Sīla (Aṭṭhasīla), meditasi, dan mendengarkan Dhamma pada puncak terang bulan.',
                'is_major' => false,
            ],
            [
                'date' => '2026-01-18',
                'title' => 'Hari Uposatha Bulan Baru (Amāvasyā / Tilem)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Tilem',
                'description' => 'Hari pembersihan batin dan perenungan Dhamma pada masa bulan mati/baru.',
                'is_major' => false,
            ],
            [
                'date' => '2026-02-02',
                'title' => 'Hari Uposatha Bulan Purnama (Purnamasiddhi)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Purnama',
                'description' => 'Hari suci pelatihan kemoralan 8 Sila & pelita puja.',
                'is_major' => false,
            ],
            [
                'date' => '2026-02-17',
                'title' => 'Hari Uposatha Bulan Baru (Amāvasyā)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Tilem',
                'description' => 'Hari hening pembinaan batin dan pelantunan paritta suci.',
                'is_major' => false,
            ],
            [
                'date' => '2026-08-13',
                'title' => 'Hari Uposatha Bulan Baru (Amāvasyā)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Tilem',
                'description' => 'Hari hening pembinaan batin dan pelantunan paritta suci masa Vassa.',
                'is_major' => false,
            ],
            [
                'date' => '2026-08-28',
                'title' => 'Hari Uposatha Bulan Purnama Masa Vassa (Purnamasiddhi)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Purnama Vassa',
                'description' => 'Hari suci puja bakti agung dan latihan meditasi hening pada masa pertengahan vassa Bhikkhu Sangha.',
                'is_major' => false,
            ],
            [
                'date' => '2026-09-11',
                'title' => 'Hari Uposatha Bulan Baru (Amāvasyā)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Tilem',
                'description' => 'Hari pembersihan batin dan perenungan sila masa Vassa.',
                'is_major' => false,
            ],
            [
                'date' => '2026-09-26',
                'title' => 'Hari Uposatha Bulan Purnama (Purnamasiddhi)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Purnama',
                'description' => 'Kebaktian agung pelita penerangan dan ceramah Dhamma menyambut akhir masa vassa.',
                'is_major' => false,
            ],
            [
                'date' => '2026-10-10',
                'title' => 'Hari Uposatha Bulan Baru (Amāvasyā)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Tilem',
                'description' => 'Hari pembinaan batin dan perenungan kebajikan.',
                'is_major' => false,
            ],
            [
                'date' => '2026-11-09',
                'title' => 'Hari Uposatha Bulan Baru (Amāvasyā)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Tilem',
                'description' => 'Hari pembersihan batin dan perenungan sila.',
                'is_major' => false,
            ],
            [
                'date' => '2026-11-24',
                'title' => 'Hari Uposatha Bulan Purnama (Purnamasiddhi)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Purnama',
                'description' => 'Kebaktian malam purnama dan puja pelita suci.',
                'is_major' => false,
            ],
            [
                'date' => '2026-12-08',
                'title' => 'Hari Uposatha Bulan Baru (Amāvasyā)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Tilem',
                'description' => 'Hari hening pembinaan batin akhir tahun.',
                'is_major' => false,
            ],
            [
                'date' => '2026-12-23',
                'title' => 'Hari Uposatha Bulan Purnama (Purnamasiddhi)',
                'type' => 'uposatha',
                'category' => 'Hari Uposatha',
                'badge' => 'Purnama',
                'description' => 'Malam purnama suci, kebaktian tutup tahun dan doa kedamaian dunia.',
                'is_major' => false,
            ],

            // --- TAHUN 2027 ---
            [
                'date' => '2027-02-21',
                'title' => 'Hari Suci Magha Puja 2570 TB',
                'type' => 'holiday',
                'category' => 'Hari Raya Buddhis',
                'badge' => 'Magha Puja',
                'description' => 'Peringatan berkumpulnya 1.250 Arahat dan pembabaran Ovāda Pāṭimokkha.',
                'is_major' => true,
            ],
            [
                'date' => '2027-05-20',
                'title' => 'Hari Raya Trisuci Waisak 2571 TB',
                'type' => 'holiday',
                'category' => 'Hari Raya Buddhis',
                'badge' => 'Trisuci Waisak',
                'description' => 'Peringatan Tiga Peristiwa Suci Kelahiran, Pencerahan Agung, dan Mahaparinibbana Buddha Gautama.',
                'is_major' => true,
            ],
            [
                'date' => '2027-07-18',
                'title' => 'Hari Suci Asadha Puja 2571 TB',
                'type' => 'holiday',
                'category' => 'Hari Raya Buddhis',
                'badge' => 'Asadha Puja',
                'description' => 'Peringatan Pemutaran Roda Dhamma pertama kali dan pembentukan Sangha pertama.',
                'is_major' => true,
            ],
            [
                'date' => '2027-10-15',
                'title' => 'Hari Raya Kathina Dāna 2571 TB',
                'type' => 'holiday',
                'category' => 'Hari Raya Buddhis',
                'badge' => 'Kathina Dāna',
                'description' => 'Perayaan persembahan jubah suci Kathina kepada Bhikkhu Sangha.',
                'is_major' => true,
            ],
        ];
    }
}
